### ISSUE TITLE
Update to latest Serverless version

### ISSUE THREAD

**Issue by jeffski** [intelygenz/serverless#1]
Please update to the latest version of Serverless - 1.30.0 at the time of writing: https://github.com/serverless/serverless/releases/tag/v1.30.0

**Comment by angelbarrera92** [comment]
Deployed @jeffski ;)
Thanks!

**Comment by angelbarrera92** [comment]
https://hub.docker.com/r/intelygenz/serverless/
https://travis-ci.org/intelygenz/serverless/builds/416254697

**Comment by jeffski** [comment]
Great, thanks for this. Just to be clear, you just need to specify the version at run time and it will just work? The Dockerfile still has version 1.26. Or did you have to create an image that you uploaded to Docker hub?

**Comment by angelbarrera92** [comment]
Hi @jeffski .

We use a Docker feature named: [build-args](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)

Dockerfile contains the build argument definition with a default value: `1.26.0`. This value is used unless you specify another one in docker build command. 

To build this image locally *(first clone this repository)*: 
```
docker build --build-arg SERVERLESS_VERSION=1.30.0 --tag my_local_serverless:1.30.0 .
```
Then, we use git tags to trigger travis pipelines. Travis will use the git tag pushed and will generate the image as follow:
```
docker build --build-arg SERVERLESS_VERSION=${GIT_TAG_PUSHED} --tag my_local_serverless:${GIT_TAG_PUSHED} .
```
So, when a new serveless version is released, we only have to tag this repository with the same version released by serverless ;).

If you have any questions, don't hesitate to ask.
